# Generated by Django 4.2.5 on 2023-09-15 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='shop',
            name='my_provider',
            field=models.ManyToManyField(related_name='shops', to='app.provider'),
        ),
    ]
